# Generated by Django 3.2.9 on 2021-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.PositiveIntegerField(verbose_name='Идентификатор пользователя')),
                ('long_link', models.CharField(max_length=255, verbose_name='Длинная ссылка пользователя')),
                ('short_link', models.CharField(max_length=10, verbose_name='Короткая ссылка пользователя')),
            ],
        ),
    ]
