# Generated by Django 3.2.9 on 2021-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='long_link',
            field=models.URLField(max_length=255, verbose_name='Длинная ссылка пользователя'),
        ),
    ]
